### ISSUE TITLE
Unable to verify certification authority

### ISSUE THREAD

**Issue by DirectedSoul1** [openshift-kni/baremetal-deploy#39] opened 2019-12-05 05:49 UTC
**Environment Used** 

OCP 4.3 IPI on BM. 

**What is the issue?**

While passing the control plane BootStrap node is unable to verify the CA, leading to API timeouts. 

**Host/Provisioner Node OS version**

```
[kni@worker-0 root]$ cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="8.1 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.1"
PLATFORM_ID="platform:el8"
```

**What is happening**

Bootstrap node is up and running:
```
[kni@worker-0 root]$ sudo virsh list
 Id    Name                           State
----------------------------------------------------
 11    kni4-ccb7p-bootstrap           running
```
All the containers inside this VM is also UP:

```
core@localhost ~]$ sudo podman ps -a |  awk '{print $NF}'
NAMES
ironic-api
ironic-inspector
ironic-conductor
sad_jones
sweet_kalam
amazing_curran
condescending_hugle
xenodochial_ptolemy
coreos-downloader
ipa-downloader
mystifying_northcutt
sad_brahmagupta
stupefied_kepler
httpd
dnsmasq
mariadb
```
The logs inside the VM states:

```
DEBUG                                              
DEBUG Apply complete! Resources: 12 added, 0 changed, 0 destroyed. 
DEBUG OpenShift Installer v4.4.0                   
DEBUG Built from commit 8aace3c8a9497f3290cd0751fd45da1a4d7c6132 
INFO Waiting up to 30m0s for the Kubernetes API at https://api.kni4.cloud.lab.eng.bos.redhat.com:6443... 
DEBUG Still waiting for the Kubernetes API: Get https://api.kni4.cloud.lab.eng.bos.redhat.com:6443/version?timeout=32s: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kube-apiserver-lb-signer") 
DEBUG Still waiting for the Kubernetes API: Get https://api.kni4.cloud.lab.eng.bos.redhat.com:6443/version?timeout=32s: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kube-apiserver-lb-signer") 
DEBUG Still waiting for the Kubernetes API: Get https://api.kni4.cloud.lab.eng.bos.redhat.com:6443/version?timeout=32s: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kube-apiserver-lb-signer") 
```

I had made sure to clean up all the older volumes and VM residues before starting this installation. 

**What was expected instead**

After the API is up , I was expecting a OCP 4.3 cluster fully functional. 

**Additional Info**

For reference, here is my install-config.yaml file 

```yaml
apiVersion: v1
baseDomain: <YourDomain> 
metadata:
  name: kni4
networking:
  machineCIDR: 10.19.136.0/21
compute:
- name: worker
  replicas: 0
controlPlane:
  name: master
  replicas: 3
  platform:
    baremetal: {}
platform:
  baremetal:
    apiVIP: 10.19.138.86 
    ingressVIP: 10.19.138.87
    dnsVIP: 10.19.138.88
    provisioningBridge: provisioning
    externalBridge: baremetal
    hosts:
      - name: openshift-master-0
        role: master
        bmc:
          address: ipmi://<URL>
          username: ***
          password: ******
        bootMACAddress: ec:f4:bb:da:0c:58
        hardwareProfile: default
      - name: ********
        role: master
        bmc:
          address: ipmi://<URL> 
          username: *****
          password: *****
        bootMACAddress: ec:f4:bb:da:32:88
        hardwareProfile: default
      - name: *********
        role: master
        bmc:
          address: ipmi://<URL>
          username: ******
          password: ******** 
        bootMACAddress: ec:f4:bb:da:0d:98
        hardwareProfile: default
pullSecret: '<YourPullSecret>'
sshKey: '<YourSSH>'
```
I have removed few lines in between, so it will not work as is.

**Comment by schmaustech** [comment] 2019-12-09 18:03
I am unable to reproduce this issue - is this consistently happening?

**Comment by rlopez133** [comment] 2019-12-09 20:05
I saw a few problems with this env. I'm trying to see if I can reproduce on existing env.

**Comment by rlopez133** [comment] 2019-12-11 23:09
I was able to successfully deploy on this specific environment with no issue. 
Things that were fixed in the environment:
- Fixed DHCP+DNS entries/records that were incorrect (likely cause of initial problem)
- Redeployed the provisioner host prior to clean installation

Not able to reproduce the issue.

**Closed by rlopez133** 2019-12-11 23:09 UTC
